### PR TITLE
Linux package only

### PR DESCRIPTION
**Pull request by hardsetting**
Making this conan package Linux-only instead of having a "fake" package.
To be applied after #1

### CODE REVIEW

**Review by jens-f — COMMENTED** [review]
I would not want to make this change and keep the ability to use this on other platforms as well. In the past, having packages that failed on some platforms was becoming a problem. It's much easier to work with them if they fail silently. We are also making available the header files on other platforms, which allows (partly) cross-platform development (excluding the linking).
See my other PR comment as well

**Comment by hardsetting** [comment]
Making this a linux-only package, and having the consumers remove the dependency to this package if the platform is not supported (which makes sense) would close the loop. How can this become a problem?

If it gives you ease of mind I can revert this change, but I think having a proper flow will potentially reduce issues with dependencies.
Let me know and I'll make the change.

**Comment by jens-f** [comment]
Consumers are still free to decide if they want to conditionally include the package. By keeping it as was it was, it will not break even if the consumer does not do that. And as I mentioned we are using the ability to have the header files available through the package even on non-Linux platforms to speed up development.

**Comment by hardsetting** [comment]
I'm not sure I got what you meant. If the (full) package only works on linux, why would a consumer want to pull the package if they're not on Linux? I think that should be prevented.

I understand you might want a simple hack to have auto-completion on OSX, but for cross compilation if you run `conan install` with a cross-compilation profile that specifies a linux platform then you would get the header files and auto-completion on smart IDEs. On CLion it's as easy as changing a value from a dropdown.

Anyway I'll revert this as it seems you feel strongly about it and don't what to discuss too long. As long as I get the control I want over dependencies for sensor-processor I'm happy.

**Pull request closed without merging**
